<div class="container mx-auto lg:mt-16 xl:mt-20 2xl:mt-24">
    <div class="w-full bg-rawl-purple lg:text-3xl xl:text-4xl text-white font-gilroy text-center lg:py-6 2xl:py-8 font-bold">We deliver on brand, stand out packaging.</div>
    <div class="grid grid-cols-4 gap-2 grid-rows-2 mt-2">
        <x-partials.homepage.case_study_block imageUrl="/images/homepage/studies/vive.jpg" imageAlt="Alt text" bg-colour="rawl-blue" linkUrl="/studies/study" linkText="Read" title="Exeter Gin" text="Morbi et porttitor metus et latinus is greatus. Curabitur ut congue neque casus studius amazingus."/>
        <x-partials.homepage.case_study_block imageUrl="/images/homepage/studies/tompom.jpg" imageAlt="Alt text" bg-colour="rawl-purple" linkUrl="/studies/study" linkText="Read" title="Exeter Gin" text="Morbi et porttitor metus et latinus is greatus. Curabitur ut congue neque casus studius amazingus."/>
        <x-partials.homepage.case_study_block imageUrl="/images/homepage/studies/vive.jpg" imageAlt="Alt text" bg-colour="rawl-purple" linkUrl="/studies/study" linkText="Read" title="Exeter Gin" text="Morbi et porttitor metus et latinus is greatus. Curabitur ut congue neque casus studius amazingus."/>
        <x-partials.homepage.case_study_block imageUrl="/images/homepage/studies/tompom.jpg" imageAlt="Alt text" bg-colour="rawl-blue" linkUrl="/studies/study" linkText="Read" title="Exeter Gin" text="Morbi et porttitor metus et latinus is greatus. Curabitur ut congue neque casus studius amazingus."/>
        <x-partials.homepage.case_study_block imageUrl="/images/homepage/studies/tompom.jpg" imageAlt="Alt text" bg-colour="rawl-purple" linkUrl="/studies/study" linkText="Read" title="Exeter Gin" text="Morbi et porttitor metus et latinus is greatus. Curabitur ut congue neque casus studius amazingus."/>
        <x-partials.homepage.case_study_block imageUrl="/images/homepage/studies/vive.jpg" imageAlt="Alt text" bg-colour="rawl-purple" linkUrl="/studies/study" linkText="Read" title="Exeter Gin" text="Morbi et porttitor metus et latinus is greatus. Curabitur ut congue neque casus studius amazingus."/>
        <x-partials.homepage.case_study_block imageUrl="/images/homepage/studies/tompom.jpg" imageAlt="Alt text" bg-colour="rawl-blue" linkUrl="/studies/study" linkText="Read" title="Exeter Gin" text="Morbi et porttitor metus et latinus is greatus. Curabitur ut congue neque casus studius amazingus."/>
        <x-partials.homepage.case_study_block imageUrl="/images/homepage/studies/vive.jpg" imageAlt="Alt text" bg-colour="rawl-green" linkUrl="/studies/study" linkText="Read" title="Exeter Gin" text="Morbi et porttitor metus et latinus is greatus. Curabitur ut congue neque casus studius amazingus."/>
    </div>
</div>